### PR TITLE
Added french translation + localized samples

### PR DESCRIPTION
**Pull request by Sladix**
Hello,

This is my first contribution to an Android project / first time I code on one too, feel free to ask me for modifications !

Also, I think that the fr sample pack should be hosted in the same place as the english one.

Love your project BTW, can't wait to set it up for my grandma :D

### CODE REVIEW

**Comment by msimonides** [comment]
Thank you, I will do my best to look through the changes in the coming week.

Right now I have one question: what is the copyright for these sample files? I assume the license allows their free use in non-commercial projects.
Please put a LICENSE file in each sample book directory with the appropriate copyright notice. I can help with that if you point me to the source of the sample files.

I will gladly incorporate your translations into the next release that I'm working on. Unfortunately I spend very little time on this project nowadays, so I need to ask you for a bit o patience, sorry about that.

**Comment by Sladix** [comment]
Thank you for your quick answer.

You are right about the license, I guess I wanted to use some samples of recent books but I just changed those for some with the creative commons license and added the proper LICENSE file in each folder !

**Review by msimonides — CHANGES_REQUESTED** [review]
Thank you for the translations.

It's the first time I'm using the code review tool on GitHub so something may be off or not clear.

I have some comments and suggestions about the code.

Also, I've started work on adding volume controls to the app, including a new setting. Please rebase your code on top of the newest changes on master.
There are several strings that have been added/modified and need to be translated or updated:

    pref_jump_back_summary
    pref_ui_options_screen_title
    pref_volume_controls
    pref_volume_controls_summary_on
    pref_volume_controls_summary_off

I'm sorry about this additional work, I hope it's not a problem. The upside is that the new functionality can be released without missing translations.

**Comment by Sladix** [comment]
Wow thanks for all the feedbacks ! I expected many as it's my first android dev, I think I misunderstood how the dependency injection works. I'm going to have to take a deeper look at dagger.
Will try to provide the updated version in the coming days !
And no worries for the additional keys

**Review by msimonides — APPROVED** [review]

**Comment by msimonides** [comment]
I would like to add you the contributors list in the README file. Do you prefer your name or nick to be added (or none)?

**Comment by Sladix** [comment]
Both are fine since my name is on my github profile. Maybe name to be consistent with the others ?

**Pull request merged**
