### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
As-is you can keep the metadata updated in this structure, and they will be pulled to my repo along with their corresponding releases (as they would with [F-Droid](https://f-droid.org/), should you want to bring your app there – which is possible now that the proprietary libraries have been removed). Using Fastlane binaries, you can even use it for deployment to Play AFAIK. If you like the idea (which I hope) and want to expand this, my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) might prove helpful.

Thanks again for providing the FOSS flavor! I hope this is something acceptable I can give back in turn :smiley:

### CODE REVIEW

**Comment by msimonides** [comment]
Thank you for providing me with this starting point. I had a quick glance at the cheat sheet and F-Droid documentation and don't see a place to put project website URL and support e-mail.

Should I put them in the full description?

**Comment by IzzySoft** [comment]
@msimonides those go to the YAML metadata file (with F-Droid and with my repo, as both are using the same software). To give you an idea:

`com.studio4plus.homerplayer.yml`

```yaml
Categories:
  - Reading
  - Multimedia
License: MIT
AuthorName: Marcin Simonides
AuthorEmail: marcin@studio4plus.com
WebSite: https://msimonides.github.io/homerplayer/
SourceCode: https://github.com/msimonides/homerplayer
IssueTracker: https://github.com/msimonides/homerplayer/issues
Changelog: https://github.com/msimonides/homerplayer/releases

...

AutoUpdateMode: Version %v
UpdateCheckMode: Tags
```

In place of the 3 dots, at F-Droid come the "build recipes" – and at my repo, some specific data to deal with updates and such (F-Droid builds from source, I pull APKs from "different places").

Of course nobody's keeping you from repeating details in the `full_description.txt` (like "for more details wisit our {website}, and also be welcome to contact us at {email}". Then users have it in "plain sight".

**Comment by IzzySoft** [comment]
@msimonides will this be merged? I'm about to drop my fork for cleanup.

**Comment by msimonides** [comment]
No, feel free to drop your fork.
I may add fastlane metadata in the future but then I will tweak it a bit (add images, more translations etc.).

**Comment by IzzySoft** [comment]
OK, a pity though. Besides: I just figured this PR would have stayed valid (and mergeable) even when I drop my fork, so you'd still have the files if needed. Guess that will be the case at least for copy-paste now though it's closed.

All the best then, I'll now drop my fork.

**Pull request closed without merging**
